[tool.poetry]
name = "data-processing-toolkit"
version = "0.1.0"
description = ""
authors = ["Dmitriy Peskov <dmitriy_peskov@ozon.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
